### ISSUE TITLE
mdown command not available

### ISSUE THREAD

**Issue by Integralist** [millermedeiros/gh-markdown-cli#1]
Hi,

Just gotten round to trying this out.

I ran the command `sudo npm install gh-markdown-cli` and this successfully installed the package...

``` sh
npm http GET https://registry.npmjs.org/gh-markdown-cli
npm http 304 https://registry.npmjs.org/gh-markdown-cli
npm http GET https://registry.npmjs.org/wrench
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/github-flavored-markdown
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/wrench
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/github-flavored-markdown
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/fast-list
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/fast-list
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/inherits
gh-markdown-cli@0.1.0 ./node_modules/gh-markdown-cli 
├── commander@0.5.2
├── wrench@1.3.5
├── github-flavored-markdown@1.0.0
├── minimatch@0.1.4 (lru-cache@1.0.5)
└── glob@3.0.1
```

But when I run the command `mdown -i src -o doc --include "*.md"` I get the response:  `-bash: mdown: command not found`

Any idea of why this would be?

**Comment by millermedeiros** [comment]
ops, my bad.. to run as a cli tool it needs to use the `-g` flag (global):

``` sh
sudo npm install gh-markdown-cli -g
```

this will create a symlink to the `bin/mdown` inside your `/usr/local/bin` folder..

**Comment by millermedeiros** [comment]
I updated the readme to include info about the `-g` flag and also updated the `package.json` including the `preferGlobal` option so if the user don't install it as global it will show a warning message.

let me know if that solves the problem. thx!

**Comment by Integralist** [comment]
Thank you, I've tried again and that seemed to work.

Can you also clarify the command itself. If I'm inside the relevant directory with the markdown files I want to convert and I want to convert just those files and save them in a sub directory of the current directory then would this be correct...

`mdown -i "./" -o "./docs/" --include "*.md"`

...as that didn't appear to work for me.

I also tried...

`mdown -i -o "./docs/" --include "*.md"` and `mdown -o "./docs/" --include "*.md"`

...but both of these caused the following error...

``` sh
buffer.js:430
      throw new Error('Unknown encoding');
            ^
Error: Unknown encoding
    at Buffer.toString (buffer.js:430:13)
    at Object.readFileSync (fs.js:155:33)
    at toMdown (/usr/local/lib/node_modules/gh-markdown-cli/mdown.js:43:23)
    at /usr/local/lib/node_modules/gh-markdown-cli/mdown.js:35:54
    at Array.forEach (native)
    at /usr/local/lib/node_modules/gh-markdown-cli/mdown.js:25:14
    at Glob.<anonymous> (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:76:41)
    at Glob.emit (events.js:67:17)
    at next (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:185:8)
    at Glob._finish (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:144:32)
```

**Comment by millermedeiros** [comment]
yes, that would be correct but since `--input` is optional and you are already inside the directory, you can simply do:

``` sh
mdown -o docs --include "*.md"
```

it will create a new folder `docs/` if it doesn't exist and generate a new HTML file for each `.md` file it finds inside the current folder.

or even:

``` sh
mdown -o docs
```

it will convert all the `.md` files it can find inside the current folder and all it's child folders.

the only option that is really required is the `--output` (`-o` as shortcut), by default it will scan all the folders and subfolders for ".md" files (the default `--include` is `"**/*.md"`) and create a separate HTML for each one into a folder of same name inside the output folder, if `-i` and `-o` are the same the HTML will be created at the same folder as the source Markdown files.

PS: `--output` is a required argument only to avoid mistakes.

**Comment by Integralist** [comment]
Thanks for the confirmation, although the script errors for me no matter what i try (it creates the folder though?)

``` sh
$ mdown -o docs --include "*.md"

buffer.js:430
      throw new Error('Unknown encoding');
            ^
Error: Unknown encoding
    at Buffer.toString (buffer.js:430:13)
    at Object.readFileSync (fs.js:155:33)
    at toMdown (/usr/local/lib/node_modules/gh-markdown-cli/mdown.js:43:23)
    at /usr/local/lib/node_modules/gh-markdown-cli/mdown.js:35:54
    at Array.forEach (native)
    at /usr/local/lib/node_modules/gh-markdown-cli/mdown.js:25:14
    at Glob.<anonymous> (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:76:41)
    at Glob.emit (events.js:67:17)
    at next (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:185:8)
    at Glob._finish (/usr/local/lib/node_modules/gh-markdown-cli/node_modules/glob/glob.js:144:32)
```

**Comment by millermedeiros** [comment]
uhm... which node version? might be something that changed on the last versions (they changed the way `readFileSync` and `writeFileSync` works since 0.4)...

I'm running v0.6.3

**Comment by millermedeiros** [comment]
damn.. just found out, stupid typo, will push v0.1.1 to npm now..

**Comment by millermedeiros** [comment]
it's up on npm!

``` sh
sudo npm update gh-markdown-cli -g
```

let me know if now it works :P

**Comment by millermedeiros** [comment]
did you tried it out?

**Comment by Integralist** [comment]
Hi, just so you know I'm now running the latest version which off the top of my head i think is 0.6.9. Sorry for the late reply I left work before you responded. I will give it a go now and let you know. Thanks.

**Comment by Integralist** [comment]
Works! Thanks :-) Now to try out the header/footer insertion
